
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/home/huang/.local/lib/python3.12/site-packages/cmake/data/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/huang/harmonyos/linux/toolchains/"
      - "/home/huang/harmonyos/linux/native/llvm/bin/"
      - "/home/huang/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/home/huang/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/home/huang/.vscode-server/bin/6a44c352bd24569c417e530095901b649960f9f8/bin/remote-cli/"
      - "/home/huang/.local/bin/"
      - "/home/huang/.nvm/versions/node/v24.14.1/bin/"
      - "/home/huang/miniconda/bin/"
      - "/home/huang/miniconda/condabin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/windows/system32/"
      - "/mnt/c/windows/"
      - "/mnt/c/windows/System32/Wbem/"
      - "/mnt/c/windows/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/windows/System32/OpenSSH/"
      - "/mnt/c/Program Files/dotnet/"
      - "/mnt/c/Program Files/nodejs/"
      - "/mnt/c/Program Files/Git/cmd/"
      - "/mnt/c/msys64/mingw64/bin/"
      - "/mnt/c/Program Files/usbipd-win/"
      - "/mnt/d/Program Files/Qoder/bin/"
      - "/mnt/c/Users/huang/AppData/Local/Microsoft/WindowsApps/"
      - "/mnt/c/Users/huang/AppData/Roaming/npm/"
      - "/mnt/c/Program Files/Huawei/DevEco Studio/bin/"
      - "/mnt/c/Users/huang/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "/mnt/c/Users/huang/.bun/bin/"
      - "/mnt/c/Program Files/Huawei/DevEco Studio/sdk/default/openharmony/toolchains/"
      - "/snap/bin/"
      - "/home/huang/.vscode-server/extensions/ms-python.debugpy-2026.6.0-linux-x64/bundled/scripts/noConfigScripts/"
      - "/home/huang/.claude/plugins/cache/claude-plugins-official/clangd-lsp/1.0.0/bin/"
      - "/home/huang/.claude/plugins/cache/claude-plugins-official/claude-md-management/1.0.0/bin/"
      - "/home/huang/.claude/plugins/cache/claude-plugins-official/code-review/unknown/bin/"
      - "/home/huang/.claude/plugins/cache/claude-plugins-official/code-simplifier/1.0.0/bin/"
      - "/home/huang/.claude/plugins/cache/claude-plugins-official/context7/unknown/bin/"
      - "/home/huang/.claude/plugins/cache/claude-plugins-official/github/unknown/bin/"
      - "/home/huang/.claude/plugins/cache/claude-plugins-official/skill-creator/unknown/bin/"
      - "/home/huang/.claude/plugins/cache/claude-plugins-official/superpowers/5.1.0/bin/"
    searched_directories:
      - "/home/huang/harmonyos/linux/toolchains/uname"
      - "/home/huang/harmonyos/linux/native/llvm/bin/uname"
      - "/home/huang/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/uname"
      - "/home/huang/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli/uname"
      - "/home/huang/.vscode-server/bin/6a44c352bd24569c417e530095901b649960f9f8/bin/remote-cli/uname"
      - "/home/huang/.local/bin/uname"
      - "/home/huang/.nvm/versions/node/v24.14.1/bin/uname"
      - "/home/huang/miniconda/bin/uname"
      - "/home/huang/miniconda/condabin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/huang/harmonyos/linux/toolchains"
        - "/home/huang/harmonyos/linux/native/llvm/bin"
        - "/home/huang/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand"
        - "/home/huang/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli"
        - "/home/huang/.vscode-server/bin/6a44c352bd24569c417e530095901b649960f9f8/bin/remote-cli"
        - "/home/huang/.local/bin"
        - "/home/huang/.nvm/versions/node/v24.14.1/bin"
        - "/home/huang/harmonyos/linux/toolchains"
        - "/home/huang/harmonyos/linux/native/llvm/bin"
        - "/home/huang/miniconda/bin"
        - "/home/huang/miniconda/condabin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/windows/system32"
        - "/mnt/c/windows"
        - "/mnt/c/windows/System32/Wbem"
        - "/mnt/c/windows/System32/WindowsPowerShell/v1.0"
        - "/mnt/c/windows/System32/OpenSSH"
        - "/mnt/c/Program Files/dotnet"
        - "/mnt/c/Program Files/nodejs"
        - "/mnt/c/Program Files/Git/cmd"
        - "/mnt/c/msys64/mingw64/bin"
        - "/mnt/c/Program Files/usbipd-win"
        - "/mnt/d/Program Files/Qoder/bin"
        - "/mnt/c/Users/huang/AppData/Local/Microsoft/WindowsApps"
        - "/mnt/c/Users/huang/AppData/Roaming/npm"
        - "/mnt/c/Program Files/Huawei/DevEco Studio/bin"
        - "/mnt/c/Users/huang/AppData/Local/Programs/Microsoft VS Code/bin"
        - "/mnt/c/Users/huang/.bun/bin"
        - "/mnt/c/Program Files/Huawei/DevEco Studio/sdk/default/openharmony/toolchains"
        - "/snap/bin"
        - "/home/huang/.vscode-server/extensions/ms-python.debugpy-2026.6.0-linux-x64/bundled/scripts/noConfigScripts"
        - "/home/huang/.claude/plugins/cache/claude-plugins-official/clangd-lsp/1.0.0/bin"
        - "/home/huang/.claude/plugins/cache/claude-plugins-official/claude-md-management/1.0.0/bin"
        - "/home/huang/.claude/plugins/cache/claude-plugins-official/code-review/unknown/bin"
        - "/home/huang/.claude/plugins/cache/claude-plugins-official/code-simplifier/1.0.0/bin"
        - "/home/huang/.claude/plugins/cache/claude-plugins-official/context7/unknown/bin"
        - "/home/huang/.claude/plugins/cache/claude-plugins-official/github/unknown/bin"
        - "/home/huang/.claude/plugins/cache/claude-plugins-official/skill-creator/unknown/bin"
        - "/home/huang/.claude/plugins/cache/claude-plugins-official/superpowers/5.1.0/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/home/huang/.local/lib/python3.12/site-packages/cmake/data/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64
...
